services:
  - type: worker
    name: wiki-service
    plan: free
    repo: https://github.com/SehunPyo/wikijs-on-render
    branch: main
    dockerCommand: docker compose up
    dockerContext: .
    autoDeploy: true
