services:
  - type: web
    name: wiki-service
    env: docker
    repo: https://github.com/SehunPyo/wikijs-on-render
    branch: main
    plan: free
    dockerfilePath: ./docker-compose.yml
    autoDeploy: true
