services:
  - type: web
    name: wiki-service
    env: docker
    plan: free
    repo: https://github.com/SehunPyo/wikijs-on-render
    branch: main
    dockerCommand: docker-compose up
    buildFilter:
      paths:
        - docker-compose.yml
